version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 9000:9000
    command:
      - bash
      - -c
      - |
        php-fpm
    networks:
      - ocr
    user: www-data

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/qwintry.pem:/etc/nginx/ssl/qwintry.pem
      - ./docker/nginx/ssl/qwintry-key.pem:/etc/nginx/ssl/qwintry-key.pem
      - .:/var/www/html
      - /etc/hosts:/etc/hosts
    depends_on:
      - app
    networks:
      - ocr

networks:
  ocr:
